### PR TITLE
Prometheus metrics wrapper

### PR DESCRIPTION
**Pull request by nicholasgibson2**
pulled in changes from elastalert master branch, see my commit for my changes
added changes requested here https://github.com/Yelp/elastalert/pull/2211
converted gauges to counters to avoid potential data loss between Prometheus scrapes.
made Prometheus server port configurable
added counter to record every rule scrape

### CODE REVIEW

**Comment by abhishek-jaisingh** [comment]
looks good @nicholasgibson2 , might take some time to properly review & test it

**Comment by nicholasgibson2** [comment]
@abhishekjiitr you get a chance to review this?

**Comment by abhishek-jaisingh** [comment]
The new class you defined certainly looks like a cleaner implementation, but I had a few questions:
1. Where exactly is the new class `PrometheusWrapper` being instantiated / hooked into the ElastAlert.
2. The methods in PrometheusWrapper class are wrappers for ElastAlert's `run_rule` & `writeback` methods. By changing the ElastAlert client's function to refer to our function, this surely solves our problem of updating the metrics, but this doesn't seem to be scalable to me (Lets say in future you want to similarly write other wrapper for some feature, you will have to wrap this new prometheus class's methods now). I would recommend just a function call to our class's method from ElastAlert's methods like run_rule. Would like to know about your though process for your implementation though.
3. Although not super critical, but we are not considering if a rule gets deleted /  modified, its stale metrics will still be exported as long as ElastAlert is running.

**Comment by nicholasgibson2** [comment]
1. Object gets instantiated in elastalert.py
```
1932    if client.prometheus_port and not client.debug:
1933        p = PrometheusWrapper(client)
```
2. Wrapper class was requested in your PR to Elastalert. https://github.com/Yelp/elastalert/pull/2211#issuecomment-490391876 Not using a wrapper would make disabling the metrics more difficult.
3. I'm not familiar with how Elastalert reloads config files. It would be nice to reset the gauges on config changes.

**Comment by andres-tw** [comment]
Any plans on merging this and updating upstream PR? @abhishekjiitr

**Comment by Shashankft9** [comment]
Hi, facing an issue getting the alerts sent and alerts not sent metrics.


Would be nice if you can verify and let me know if I am doing something wrong here.

```
elastalert_matches_created{rule_name="rule1"} 1.580884045686973e+09
# HELP elastalert_time_taken_total Time taken to evaluate rule
# TYPE elastalert_time_taken_total counter
elastalert_time_taken_total{rule_name="rule1"} 1.450749158859253
# TYPE elastalert_time_taken_created gauge
elastalert_time_taken_created{rule_name="rule1"} 1.5808840456870105e+09
# HELP elastalert_alerts_sent_total Number of alerts sent for rule
# TYPE elastalert_alerts_sent_total counter
# HELP elastalert_alerts_not_sent_total Number of alerts not sent for rule
# TYPE elastalert_alerts_not_sent_total counter
# HELP elastalert_errors_total Number of errors for rule
# TYPE elastalert_errors_total counter
elastalert_errors_total 0.0

```

**Comment by nicholasgibson2** [comment]
@Shashankft9 doesn't look like you're doing anything wrong since other metrics are being generated. Age old problem of "it works on my machine ¯\\_(ツ)_/¯"

**Comment by Shashankft9** [comment]
@nicholasgibson2 I am hoping it isn't that, that would pretty much be a dead-end. 
I'll rerun it. 
I see that you were able to fix the build issues, lets hope it gets committed as well, would be nice.
@Qmando

**Comment by Shashankft9** [comment]
@nicholasgibson2 all the metrics are registered, as elastalert goes onto querying, taking hits and matches it then starts incrementing the values of these metrics, but i notice that just  
```
 elastalert_alerts_sent_total
```
and 
```
elastalert_alerts_not_sent_total
```
are not incremented. I see the logs using --verbose and it throws the following error:
```
ERROR:root:Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1453, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1562, in send_alert
    res = self.writeback('elastalert', alert_body, rule)
TypeError: metrics_writeback() takes 3 positional arguments but 4 were given

ERROR:root:Uncaught exception running rule rule1: metrics_writeback() takes 3 positional arguments but 4 were given
```
perhaps this could be the reason why?

**Comment by Shashankft9** [comment]
@nicholasgibson2 opinions?

**Pull request closed without merging**
